theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: Paul Muller, Research Scientist
description: (Multiagent) Reinforcement Learning, Game Theory, Large Language Models, Political Philosophy, Muay Thai.
