theme: cayman
logo: /assets/img/signal-2024-01-17-20-12-18-596.jpg
title: Paul Muller
description: (Multiagent) Reinforcement Learning, Game Theory, Large Language Models, Political Philosophy, Muay Thai.
